# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - '*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
  TargetRubyVersion: 4.0 
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Rails/SkipsModelValidations:
  Exclude:
    - 'app/services/schedule_sync.rb'

Rails/UniqueValidationWithoutIndex:
  Exclude:
    - 'app/models/user_profile.rb'

